name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Pull commits
        run: git pull origin master

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: npm run build
